#!/usr/bin/python

#########################################################################
### Declarations ########################################################
#########################################################################

import puppetdb, sys

#########################################################################
### Configuration #######################################################
#########################################################################

## Text for --help
help_text = "query puppetdb to list all hosts"
usage_text = "usage: %prog [options] [HOSTPATTERN]"

#########################################################################
### main () #############################################################
#########################################################################

def main():
    p = puppetdb.generateParser(help_text, usage_text)
    opt, args = p.parse_args()

    if len(args) < 1:   host_search = '.*'
    else:               host_search = args[0]

    query = "['~', ['fact', 'fqdn'], '^%s$']" % host_search
    try:
        for node in puppetdb.queryNodes(query, opt):
            if 'certname' in node: print node['certname']
            elif 'name' in node:   print node['name']
    except Exception, e:
        print "error: %s" % e

    sys.exit(0)

if __name__ == '__main__':
    main()

#########################################################################
### POD Documentation ###################################################
#########################################################################
## We use this to generate man pages.

"""

=head1 NAME

puppetdb-hosts - list hosts in the puppetdb

=head1 SYNOPSYS

B<puppetdb-hosts>

B<puppetdb-hosts> cms.\*.fnal.gov

=head1 USAGE

puppetdb-hosts queries the puppetdb to find a list of hosts, and prints it
to STDOUT.

Should support both v3 and v4 PuppetDB APIs.

=head1 OPTIONS

=over 4

=item I<HOSTPATTERN>

Default host pattern to match.  Defaults to '.*'; remember that you may
need to escape wild cards if you're using this from the CLI.

=item --help

Prints some short help documentation and exits.

=back

=head1 AUTHOR

Tim Skirvin <tskirvin@fnal.gov>

=head1 COPYRIGHT

Copyright 2015-2016, Fermi National Accelerator Laboratory

This program is free software; you may redistribute it and/or modify
it under the same terms as Perl itself.

=cut

"""
