#!/usr/bin/python

#########################################################################
### Configuration #######################################################
#########################################################################

config_file = '/etc/puppetdb/puppetdb.json'

#########################################################################
### Declarations ########################################################
#########################################################################

from datetime import datetime, timedelta
import dateutil.parser, dateutil.tz
import json, optparse, re, requests, sys

## this isn't ideal, but until I actually start verifying the cert this
## is the best I can do
from requests.packages.urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

#########################################################################
### Subroutines #########################################################
#########################################################################

def parseConfig(file):
    """
    Load a json configuration from a configuration file.  Sets a global
    'config' variable.
    """
    global config

    try:
        config = json.load(open(config_file, 'r'))
    except IOError, e:
        print "file error:  %s" % e
        sys.exit (2)
    except Exception, e:
        print "unknown error:  %s" % e
        sys.exit (2)

    return config


def hostFact(fact):
    """
    Return a hash of name-to-fact values for a given fact.
    """
    query = "['~', 'name', '%s']" % fact
    try:
        payload = { 'query': json.dumps(eval(query))}
    except SyntaxError:
        p.error('Malformed query, check examples for help')

    if opt.debug:
        print "payload: %s" % payload

    headers = {'Accept': 'application/json'}
    try:
        url = "%s%s" % ( opt.server, opt.facts_url_base )
        r = requests.get(url, headers=headers, params=payload, 
            cert=requestCert(url), verify=False)
    except Exception, e:
        p.error('%s (bad json?: %s)' % (e, payload))

    if len(r.json()) == 0:
        print "no matches"
        sys.exit(-1)

    hash = {}
    for node in r.json():
        name = node['certname']
        fs = node['name']
        uuid = node['value']
        if name in hash:
            hash[name][fs] = uuid
        else:
            hash[name] = {}
            hash[name][fs] = uuid


    return hash

def hostUuid():   return hostFact('uuid__*')

def requestCert(url):
    """
    If the URL is https, then we will need to pass config['cert'] and
    config['key'].
    """
    if re.match('^https:', url):
        r = (config['cert'], config['key'])
    else:
        r = ()

    return r

#########################################################################
### main () #############################################################
#########################################################################

def main():
    usage = "%prog [options] [HOSTPATTERN]"
    parseConfig(config_file)

    global p
    p = optparse.OptionParser (usage = usage,
        description = "query puppetdb for facts from matching hosts")
    p.add_option ('--debug', dest='debug', action='store_true', default=False)
    p.add_option ('--server', dest='server', default=config['server'],
        help="puppetdb server (default: %default)")
    p.add_option ('--facts_url_base', dest='facts_url_base',
        default=config['facts_url_base'],
        help="relative URL to puppetdb for default facts query")

    global opt
    opt, args = p.parse_args()

    uuids = hostUuid()

    for host in sorted (uuids.keys()):
        for disk in sorted (uuids[host].keys()):
            item = []
            item.append (host)
            disk_short = re.sub("^uuid__", "", disk)
            item.append (disk_short)
            item.append (uuids[host][disk])

            print "%s %s %s" % (item[0], item[2], item[1])

    sys.exit(0)

if __name__ == '__main__':
    main()

#########################################################################
### POD Documentation ###################################################
#########################################################################
## We use this to generate man pages.

"""

=head1 NAME

puppetdb-uuid-by-host - list all uuid_* facts

=head1 SYNOPSYS

B<puppetdb-uuid-by-host>

=head1 USAGE

puppetdb-uuid-by-host queries the puppetdb to find all system facts
matching 'uuid__', and prints the appropriate report via STDOUT.

=head1 OPTIONS

=over 4

=item --help

Prints some short help documentation and exits.

=back

=head1 AUTHOR

Tim Skirvin <tskirvin@fnal.gov>

=head1 COPYRIGHT

Copyright 2015, Fermi National Accelerator Laboratory

This program is free software; you may redistribute it and/or modify
it under the same terms as Perl itself.

=cut

"""
