#!/usr/bin/python

#########################################################################
### Declarations ########################################################
#########################################################################

import puppetdb, sys

#########################################################################
### Configuration #######################################################
#########################################################################

## Text for --help
help_text = "query puppetdb for hosts that failed their last run, with reasons"
usage_text = "usage: %prog [options] [HOSTPATTERN]"

#########################################################################
### main () #############################################################
#########################################################################

def main():
    p = puppetdb.generateParser(help_text, usage_text)
    opt, args = p.parse_args()

    if len(args) < 1:   host_search = '.*'
    else:               host_search = args[0]

    failed = puppetdb.nodesFailed (host_search, opt)
    if len(failed) == 0: sys.exit(0)

    nodes = puppetdb.nodesList(host_search, opt)

    for i in sorted(failed):
        if i in nodes:
            failures = puppetdb.hostFailedWhy(i, opt)
            print "Node %s - %d failures" % (i, len(failures))
            for j in failures:
                print "  %s" % j
            print ""

    sys.exit(0)

if __name__ == '__main__':
    main()

#########################################################################
### POD Documentation ###################################################
#########################################################################
## We use this to generate man pages.

"""

=head1 NAME

puppetdb-failed-list - list events that failed, on a per-host basis

=head1 SYNOPSYS

B<puppetdb-failed-list>

B<puppetdb-failed-list> cmssrv.\*.fnal.gov

=head1 USAGE

puppetdb-failed-list queries the puppetdb to find hosts which had a
failure in their last run, and reports on each of those failures to
STDOUT.

The list of associated events is printed on STDOUT, in the format:

    Node d0cs3093.fnal.gov - 2 failures
      Augeas[add clogger.fnal.gov to log service]: None -> None (Saving failed, see debug)
      Augeas[add fefadmin03 as log host]: None -> None (Saving failed, see debug)

Should support both v3 and v4 PuppetDB APIs.

=head1 OPTIONS

=over 4

=item I<HOSTPATTERN>

Default host pattern to match.  Defaults to '.*'; remember that you may
need to escape wild cards if you're using this from the CLI.

=item --help

Prints some short help documentation and exits.

=back

=head1 AUTHOR

Tim Skirvin <tskirvin@fnal.gov>

Based in part on https://github.com/JHaals/puppetdb-grep

=head1 COPYRIGHT

Copyright 2014-2016, Fermi National Accelerator Laboratory

This program is free software; you may redistribute it and/or modify it
under the same terms as Perl itself.

=cut

"""
